### ISSUE TITLE
It's not completely clear why lock files are `.gitignore`d

### ISSUE THREAD

**Issue by Aquaticat** [run-z/run-z#57]
`.gitignore`:

```gitignore
# Lock files as this is part of Yarn worktree
yarn.lock
package-lock.json
```

However, [Stackoverflow says these files should not be ignored](https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files)

A reason should be provided as to why "Yarn worktree" should impact the decision to ignore this files.

**Comment by surol** [comment]
True, but doesn't wok with my particular setup. Let me explain why:

All projects, despite hosted in individual repositories, live in one (private) pnpm work tree. That's the only viable way to debug them. That's why I can't maintain individual lockfiles. The pnpm work tree maintains only one at the root level.

**Comment by Aquaticat** [comment]
You should make it clear that it's because of your personal setup, then.

By the way, I'm curious to why you decided to make different projects live in one private pnpm work tree.

**Comment by Aquaticat** [comment]
I thought about opening a pull request for this but since this is due to your personal setup I think it's best be done by you.

**Comment by surol** [comment]
Those projects are different, but very connected. For example, the whole `@proc7ts` set of libraries used by `run-z`, and in many other projects too. Including private ones, that use everything altogether.

So, when I am trying to find a bug, I need a full set of projects within a work tree. This way, I can quickly apply changes to the library and test whether it fixes/breaks something in other projects. Otherwise, the maintenance would turn into a nightmare. It actually was, until I started using workspaces and implemented `run-z` on top of this.

**Comment by Aquaticat** [comment]
That's actually brilliant!

This should absolutely be documented.

If these projects are this connected, you should share your setup so other potential maintainer don't meet the same problem as you did.
