### ISSUE TITLE
Support json5

### ISSUE THREAD

**Issue by jascodes** [run-z/run-z#66]
Please add support for awesome json5 by alternatively reading package.json5.

Thanks

@surol 
@Aquaticat

**Comment by surol** [comment]
There is no point in supporting JSON5 (or other formats) by `run-z` until Node.js and package managers support it in the first place.

There is a [proposal](https://github.com/npm/rfcs/issues/291) for this and a [discussion](https://github.com/npm/feedback/discussions/56). Seems like not going to happen.

**Comment by jascodes** [comment]
@surol I use PNPM and they already do.

**Comment by surol** [comment]
Ah, didn't know that, despite I am using `pnpm` too. Not a word in official documentation, weird.

However, I still see problems because of the lack of support in Node.js. E.g. `"type": "module"` should be in `package.json`. This is a huge drawback to me.
Also, once we are speaking about non-standard package formats, we also have to mention `package.yaml`.

Well, I'll change my mind from "unlikely" to "maybe". May be as an extension. When/if extensions support will be added.

**Comment by jascodes** [comment]
Okay fair enough buddy
